#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
	(
		echo '
            Prettier Check Failed. Run npm run format, add changes and try commit again.'
		false
	)

# Check ESLint Standards
npm run check-lint ||
	(
		echo '
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
		false
	)

# Check tsconfig standards
npm run check-types ||
	(
		echo '
            TypeCheck Error!!!! Make the changes required above.'
		false
	)

npm run test ||
	(
		echo '
            Tests Failed!!!! Fix your tests first'
		false
	)
# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
