name: compile-workflow
on: [pull_request]
jobs:
  compile-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install --save-dev
      - run: npm run compile
